{- This file was auto-generated from network_connection.proto by the proto-lens-protoc program. -}
{-# LANGUAGE ScopedTypeVariables, DataKinds, TypeFamilies, UndecidableInstances, GeneralizedNewtypeDeriving, MultiParamTypeClasses, FlexibleContexts, FlexibleInstances, PatternSynonyms, MagicHash, NoImplicitPrelude, DataKinds, BangPatterns, TypeApplications, OverloadedStrings, DerivingStrategies#-}
{-# OPTIONS_GHC -Wno-unused-imports#-}
{-# OPTIONS_GHC -Wno-duplicate-exports#-}
{-# OPTIONS_GHC -Wno-dodgy-exports#-}
module Proto.NetworkConnection (
        ENetworkDisconnectionReason(..), ENetworkDisconnectionReason()
    ) where
import qualified Data.ProtoLens.Runtime.Control.DeepSeq as Control.DeepSeq
import qualified Data.ProtoLens.Runtime.Data.ProtoLens.Prism as Data.ProtoLens.Prism
import qualified Data.ProtoLens.Runtime.Prelude as Prelude
import qualified Data.ProtoLens.Runtime.Data.Int as Data.Int
import qualified Data.ProtoLens.Runtime.Data.Monoid as Data.Monoid
import qualified Data.ProtoLens.Runtime.Data.Word as Data.Word
import qualified Data.ProtoLens.Runtime.Data.ProtoLens as Data.ProtoLens
import qualified Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Bytes as Data.ProtoLens.Encoding.Bytes
import qualified Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Growing as Data.ProtoLens.Encoding.Growing
import qualified Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Parser.Unsafe as Data.ProtoLens.Encoding.Parser.Unsafe
import qualified Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Wire as Data.ProtoLens.Encoding.Wire
import qualified Data.ProtoLens.Runtime.Data.ProtoLens.Field as Data.ProtoLens.Field
import qualified Data.ProtoLens.Runtime.Data.ProtoLens.Message.Enum as Data.ProtoLens.Message.Enum
import qualified Data.ProtoLens.Runtime.Data.ProtoLens.Service.Types as Data.ProtoLens.Service.Types
import qualified Data.ProtoLens.Runtime.Lens.Family2 as Lens.Family2
import qualified Data.ProtoLens.Runtime.Lens.Family2.Unchecked as Lens.Family2.Unchecked
import qualified Data.ProtoLens.Runtime.Data.Text as Data.Text
import qualified Data.ProtoLens.Runtime.Data.Map as Data.Map
import qualified Data.ProtoLens.Runtime.Data.ByteString as Data.ByteString
import qualified Data.ProtoLens.Runtime.Data.ByteString.Char8 as Data.ByteString.Char8
import qualified Data.ProtoLens.Runtime.Data.Text.Encoding as Data.Text.Encoding
import qualified Data.ProtoLens.Runtime.Data.Vector as Data.Vector
import qualified Data.ProtoLens.Runtime.Data.Vector.Generic as Data.Vector.Generic
import qualified Data.ProtoLens.Runtime.Data.Vector.Unboxed as Data.Vector.Unboxed
import qualified Data.ProtoLens.Runtime.Text.Read as Text.Read

data ENetworkDisconnectionReason
  = NETWORK_DISCONNECT_INVALID |
    NETWORK_DISCONNECT_SHUTDOWN |
    NETWORK_DISCONNECT_DISCONNECT_BY_USER |
    NETWORK_DISCONNECT_DISCONNECT_BY_SERVER |
    NETWORK_DISCONNECT_LOST |
    NETWORK_DISCONNECT_OVERFLOW |
    NETWORK_DISCONNECT_STEAM_BANNED |
    NETWORK_DISCONNECT_STEAM_INUSE |
    NETWORK_DISCONNECT_STEAM_TICKET |
    NETWORK_DISCONNECT_STEAM_LOGON |
    NETWORK_DISCONNECT_STEAM_AUTHCANCELLED |
    NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED |
    NETWORK_DISCONNECT_STEAM_AUTHINVALID |
    NETWORK_DISCONNECT_STEAM_VACBANSTATE |
    NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE |
    NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT |
    NETWORK_DISCONNECT_STEAM_DROPPED |
    NETWORK_DISCONNECT_STEAM_OWNERSHIP |
    NETWORK_DISCONNECT_SERVERINFO_OVERFLOW |
    NETWORK_DISCONNECT_TICKMSG_OVERFLOW |
    NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW |
    NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW |
    NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW |
    NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW |
    NETWORK_DISCONNECT_SNAPSHOTOVERFLOW |
    NETWORK_DISCONNECT_SNAPSHOTERROR |
    NETWORK_DISCONNECT_RELIABLEOVERFLOW |
    NETWORK_DISCONNECT_BADDELTATICK |
    NETWORK_DISCONNECT_NOMORESPLITS |
    NETWORK_DISCONNECT_TIMEDOUT |
    NETWORK_DISCONNECT_DISCONNECTED |
    NETWORK_DISCONNECT_LEAVINGSPLIT |
    NETWORK_DISCONNECT_DIFFERENTCLASSTABLES |
    NETWORK_DISCONNECT_BADRELAYPASSWORD |
    NETWORK_DISCONNECT_BADSPECTATORPASSWORD |
    NETWORK_DISCONNECT_HLTVRESTRICTED |
    NETWORK_DISCONNECT_NOSPECTATORS |
    NETWORK_DISCONNECT_HLTVUNAVAILABLE |
    NETWORK_DISCONNECT_HLTVSTOP |
    NETWORK_DISCONNECT_KICKED |
    NETWORK_DISCONNECT_BANADDED |
    NETWORK_DISCONNECT_KICKBANADDED |
    NETWORK_DISCONNECT_HLTVDIRECT |
    NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA |
    NETWORK_DISCONNECT_PURESERVER_MISMATCH |
    NETWORK_DISCONNECT_USERCMD |
    NETWORK_DISCONNECT_REJECTED_BY_GAME |
    NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR |
    NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR |
    NETWORK_DISCONNECT_BAD_SERVER_PASSWORD |
    NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION |
    NETWORK_DISCONNECT_CONNECTION_FAILURE |
    NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS |
    NETWORK_DISCONNECT_RECONNECTION |
    NETWORK_DISCONNECT_LOOPSHUTDOWN |
    NETWORK_DISCONNECT_LOOPDEACTIVATE |
    NETWORK_DISCONNECT_HOST_ENDGAME |
    NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE |
    NETWORK_DISCONNECT_CREATE_SERVER_FAILED |
    NETWORK_DISCONNECT_EXITING |
    NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE |
    NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY |
    NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL |
    NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP |
    NETWORK_DISCONNECT_CLIENT_NO_MAP |
    NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP |
    NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM |
    NETWORK_DISCONNECT_STEAM_DENY_MISC |
    NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT |
    NETWORK_DISCONNECT_SERVER_SHUTDOWN |
    NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE |
    NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT |
    NETWORK_DISCONNECT_SERVER_INCOMPATIBLE |
    NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS |
    NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY |
    NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG |
    NETWORK_DISCONNECT_LOCALPROBLEM_OTHER |
    NETWORK_DISCONNECT_REMOTE_TIMEOUT |
    NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING |
    NETWORK_DISCONNECT_REMOTE_OTHER |
    NETWORK_DISCONNECT_REMOTE_BADCRYPT |
    NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED |
    NETWORK_DISCONNECT_UNUSUAL |
    NETWORK_DISCONNECT_INTERNAL_ERROR |
    NETWORK_DISCONNECT_REJECT_BADCHALLENGE |
    NETWORK_DISCONNECT_REJECT_NOLOBBY |
    NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP |
    NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER |
    NETWORK_DISCONNECT_REJECT_HIDDEN_GAME |
    NETWORK_DISCONNECT_REJECT_LANRESTRICT |
    NETWORK_DISCONNECT_REJECT_BADPASSWORD |
    NETWORK_DISCONNECT_REJECT_SERVERFULL |
    NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION |
    NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL |
    NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY |
    NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY |
    NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH |
    NETWORK_DISCONNECT_REJECT_OLDPROTOCOL |
    NETWORK_DISCONNECT_REJECT_NEWPROTOCOL |
    NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION |
    NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN |
    NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN |
    NETWORK_DISCONNECT_REJECT_STEAM |
    NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED |
    NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID |
    NETWORK_DISCONNECT_REJECT_BANNED |
    NETWORK_DISCONNECT_KICKED_TEAMKILLING |
    NETWORK_DISCONNECT_KICKED_TK_START |
    NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT |
    NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT |
    NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN |
    NETWORK_DISCONNECT_KICKED_TEAMHURTING |
    NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING |
    NETWORK_DISCONNECT_KICKED_VOTEDOFF |
    NETWORK_DISCONNECT_KICKED_IDLE |
    NETWORK_DISCONNECT_KICKED_SUICIDE |
    NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN |
    NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET |
    NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION |
    NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR |
    NETWORK_DISCONNECT_KICKED_INSECURECLIENT
  deriving stock (Prelude.Show, Prelude.Eq, Prelude.Ord)
instance Data.ProtoLens.MessageEnum ENetworkDisconnectionReason where
  maybeToEnum 0 = Prelude.Just NETWORK_DISCONNECT_INVALID
  maybeToEnum 1 = Prelude.Just NETWORK_DISCONNECT_SHUTDOWN
  maybeToEnum 2 = Prelude.Just NETWORK_DISCONNECT_DISCONNECT_BY_USER
  maybeToEnum 3
    = Prelude.Just NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
  maybeToEnum 4 = Prelude.Just NETWORK_DISCONNECT_LOST
  maybeToEnum 5 = Prelude.Just NETWORK_DISCONNECT_OVERFLOW
  maybeToEnum 6 = Prelude.Just NETWORK_DISCONNECT_STEAM_BANNED
  maybeToEnum 7 = Prelude.Just NETWORK_DISCONNECT_STEAM_INUSE
  maybeToEnum 8 = Prelude.Just NETWORK_DISCONNECT_STEAM_TICKET
  maybeToEnum 9 = Prelude.Just NETWORK_DISCONNECT_STEAM_LOGON
  maybeToEnum 10
    = Prelude.Just NETWORK_DISCONNECT_STEAM_AUTHCANCELLED
  maybeToEnum 11
    = Prelude.Just NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED
  maybeToEnum 12 = Prelude.Just NETWORK_DISCONNECT_STEAM_AUTHINVALID
  maybeToEnum 13 = Prelude.Just NETWORK_DISCONNECT_STEAM_VACBANSTATE
  maybeToEnum 14
    = Prelude.Just NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE
  maybeToEnum 15
    = Prelude.Just NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
  maybeToEnum 16 = Prelude.Just NETWORK_DISCONNECT_STEAM_DROPPED
  maybeToEnum 17 = Prelude.Just NETWORK_DISCONNECT_STEAM_OWNERSHIP
  maybeToEnum 18
    = Prelude.Just NETWORK_DISCONNECT_SERVERINFO_OVERFLOW
  maybeToEnum 19 = Prelude.Just NETWORK_DISCONNECT_TICKMSG_OVERFLOW
  maybeToEnum 20
    = Prelude.Just NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW
  maybeToEnum 21
    = Prelude.Just NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW
  maybeToEnum 22
    = Prelude.Just NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW
  maybeToEnum 23 = Prelude.Just NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW
  maybeToEnum 24 = Prelude.Just NETWORK_DISCONNECT_SNAPSHOTOVERFLOW
  maybeToEnum 25 = Prelude.Just NETWORK_DISCONNECT_SNAPSHOTERROR
  maybeToEnum 26 = Prelude.Just NETWORK_DISCONNECT_RELIABLEOVERFLOW
  maybeToEnum 27 = Prelude.Just NETWORK_DISCONNECT_BADDELTATICK
  maybeToEnum 28 = Prelude.Just NETWORK_DISCONNECT_NOMORESPLITS
  maybeToEnum 29 = Prelude.Just NETWORK_DISCONNECT_TIMEDOUT
  maybeToEnum 30 = Prelude.Just NETWORK_DISCONNECT_DISCONNECTED
  maybeToEnum 31 = Prelude.Just NETWORK_DISCONNECT_LEAVINGSPLIT
  maybeToEnum 32
    = Prelude.Just NETWORK_DISCONNECT_DIFFERENTCLASSTABLES
  maybeToEnum 33 = Prelude.Just NETWORK_DISCONNECT_BADRELAYPASSWORD
  maybeToEnum 34
    = Prelude.Just NETWORK_DISCONNECT_BADSPECTATORPASSWORD
  maybeToEnum 35 = Prelude.Just NETWORK_DISCONNECT_HLTVRESTRICTED
  maybeToEnum 36 = Prelude.Just NETWORK_DISCONNECT_NOSPECTATORS
  maybeToEnum 37 = Prelude.Just NETWORK_DISCONNECT_HLTVUNAVAILABLE
  maybeToEnum 38 = Prelude.Just NETWORK_DISCONNECT_HLTVSTOP
  maybeToEnum 39 = Prelude.Just NETWORK_DISCONNECT_KICKED
  maybeToEnum 40 = Prelude.Just NETWORK_DISCONNECT_BANADDED
  maybeToEnum 41 = Prelude.Just NETWORK_DISCONNECT_KICKBANADDED
  maybeToEnum 42 = Prelude.Just NETWORK_DISCONNECT_HLTVDIRECT
  maybeToEnum 43
    = Prelude.Just NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA
  maybeToEnum 44
    = Prelude.Just NETWORK_DISCONNECT_PURESERVER_MISMATCH
  maybeToEnum 45 = Prelude.Just NETWORK_DISCONNECT_USERCMD
  maybeToEnum 46 = Prelude.Just NETWORK_DISCONNECT_REJECTED_BY_GAME
  maybeToEnum 47
    = Prelude.Just NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR
  maybeToEnum 48
    = Prelude.Just NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR
  maybeToEnum 49
    = Prelude.Just NETWORK_DISCONNECT_BAD_SERVER_PASSWORD
  maybeToEnum 50
    = Prelude.Just NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION
  maybeToEnum 51 = Prelude.Just NETWORK_DISCONNECT_CONNECTION_FAILURE
  maybeToEnum 52
    = Prelude.Just NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS
  maybeToEnum 53 = Prelude.Just NETWORK_DISCONNECT_RECONNECTION
  maybeToEnum 54 = Prelude.Just NETWORK_DISCONNECT_LOOPSHUTDOWN
  maybeToEnum 55 = Prelude.Just NETWORK_DISCONNECT_LOOPDEACTIVATE
  maybeToEnum 56 = Prelude.Just NETWORK_DISCONNECT_HOST_ENDGAME
  maybeToEnum 57
    = Prelude.Just NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE
  maybeToEnum 58
    = Prelude.Just NETWORK_DISCONNECT_CREATE_SERVER_FAILED
  maybeToEnum 59 = Prelude.Just NETWORK_DISCONNECT_EXITING
  maybeToEnum 60
    = Prelude.Just NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE
  maybeToEnum 61
    = Prelude.Just NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY
  maybeToEnum 62
    = Prelude.Just NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL
  maybeToEnum 63
    = Prelude.Just NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP
  maybeToEnum 64 = Prelude.Just NETWORK_DISCONNECT_CLIENT_NO_MAP
  maybeToEnum 65
    = Prelude.Just NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP
  maybeToEnum 66
    = Prelude.Just NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM
  maybeToEnum 67 = Prelude.Just NETWORK_DISCONNECT_STEAM_DENY_MISC
  maybeToEnum 68
    = Prelude.Just NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT
  maybeToEnum 69 = Prelude.Just NETWORK_DISCONNECT_SERVER_SHUTDOWN
  maybeToEnum 71
    = Prelude.Just NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE
  maybeToEnum 72
    = Prelude.Just NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
  maybeToEnum 73
    = Prelude.Just NETWORK_DISCONNECT_SERVER_INCOMPATIBLE
  maybeToEnum 74
    = Prelude.Just NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS
  maybeToEnum 75
    = Prelude.Just
        NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
  maybeToEnum 76
    = Prelude.Just NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG
  maybeToEnum 77 = Prelude.Just NETWORK_DISCONNECT_LOCALPROBLEM_OTHER
  maybeToEnum 79 = Prelude.Just NETWORK_DISCONNECT_REMOTE_TIMEOUT
  maybeToEnum 80
    = Prelude.Just NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING
  maybeToEnum 81 = Prelude.Just NETWORK_DISCONNECT_REMOTE_OTHER
  maybeToEnum 82 = Prelude.Just NETWORK_DISCONNECT_REMOTE_BADCRYPT
  maybeToEnum 83
    = Prelude.Just NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED
  maybeToEnum 84 = Prelude.Just NETWORK_DISCONNECT_UNUSUAL
  maybeToEnum 85 = Prelude.Just NETWORK_DISCONNECT_INTERNAL_ERROR
  maybeToEnum 128
    = Prelude.Just NETWORK_DISCONNECT_REJECT_BADCHALLENGE
  maybeToEnum 129 = Prelude.Just NETWORK_DISCONNECT_REJECT_NOLOBBY
  maybeToEnum 130
    = Prelude.Just NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP
  maybeToEnum 131
    = Prelude.Just NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER
  maybeToEnum 132
    = Prelude.Just NETWORK_DISCONNECT_REJECT_HIDDEN_GAME
  maybeToEnum 133
    = Prelude.Just NETWORK_DISCONNECT_REJECT_LANRESTRICT
  maybeToEnum 134
    = Prelude.Just NETWORK_DISCONNECT_REJECT_BADPASSWORD
  maybeToEnum 135 = Prelude.Just NETWORK_DISCONNECT_REJECT_SERVERFULL
  maybeToEnum 136
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION
  maybeToEnum 137
    = Prelude.Just NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL
  maybeToEnum 138
    = Prelude.Just NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY
  maybeToEnum 139
    = Prelude.Just NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY
  maybeToEnum 140
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH
  maybeToEnum 141
    = Prelude.Just NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
  maybeToEnum 142
    = Prelude.Just NETWORK_DISCONNECT_REJECT_NEWPROTOCOL
  maybeToEnum 143
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION
  maybeToEnum 144
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN
  maybeToEnum 145
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN
  maybeToEnum 146 = Prelude.Just NETWORK_DISCONNECT_REJECT_STEAM
  maybeToEnum 147
    = Prelude.Just NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED
  maybeToEnum 148
    = Prelude.Just NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID
  maybeToEnum 149 = Prelude.Just NETWORK_DISCONNECT_REJECT_BANNED
  maybeToEnum 150
    = Prelude.Just NETWORK_DISCONNECT_KICKED_TEAMKILLING
  maybeToEnum 151 = Prelude.Just NETWORK_DISCONNECT_KICKED_TK_START
  maybeToEnum 152
    = Prelude.Just NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT
  maybeToEnum 153
    = Prelude.Just NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT
  maybeToEnum 154
    = Prelude.Just NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN
  maybeToEnum 155
    = Prelude.Just NETWORK_DISCONNECT_KICKED_TEAMHURTING
  maybeToEnum 156
    = Prelude.Just NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING
  maybeToEnum 157 = Prelude.Just NETWORK_DISCONNECT_KICKED_VOTEDOFF
  maybeToEnum 158 = Prelude.Just NETWORK_DISCONNECT_KICKED_IDLE
  maybeToEnum 159 = Prelude.Just NETWORK_DISCONNECT_KICKED_SUICIDE
  maybeToEnum 160
    = Prelude.Just NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN
  maybeToEnum 161
    = Prelude.Just NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET
  maybeToEnum 162
    = Prelude.Just NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION
  maybeToEnum 163
    = Prelude.Just NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR
  maybeToEnum 164
    = Prelude.Just NETWORK_DISCONNECT_KICKED_INSECURECLIENT
  maybeToEnum _ = Prelude.Nothing
  showEnum NETWORK_DISCONNECT_INVALID = "NETWORK_DISCONNECT_INVALID"
  showEnum NETWORK_DISCONNECT_SHUTDOWN
    = "NETWORK_DISCONNECT_SHUTDOWN"
  showEnum NETWORK_DISCONNECT_DISCONNECT_BY_USER
    = "NETWORK_DISCONNECT_DISCONNECT_BY_USER"
  showEnum NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
    = "NETWORK_DISCONNECT_DISCONNECT_BY_SERVER"
  showEnum NETWORK_DISCONNECT_LOST = "NETWORK_DISCONNECT_LOST"
  showEnum NETWORK_DISCONNECT_OVERFLOW
    = "NETWORK_DISCONNECT_OVERFLOW"
  showEnum NETWORK_DISCONNECT_STEAM_BANNED
    = "NETWORK_DISCONNECT_STEAM_BANNED"
  showEnum NETWORK_DISCONNECT_STEAM_INUSE
    = "NETWORK_DISCONNECT_STEAM_INUSE"
  showEnum NETWORK_DISCONNECT_STEAM_TICKET
    = "NETWORK_DISCONNECT_STEAM_TICKET"
  showEnum NETWORK_DISCONNECT_STEAM_LOGON
    = "NETWORK_DISCONNECT_STEAM_LOGON"
  showEnum NETWORK_DISCONNECT_STEAM_AUTHCANCELLED
    = "NETWORK_DISCONNECT_STEAM_AUTHCANCELLED"
  showEnum NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED
    = "NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED"
  showEnum NETWORK_DISCONNECT_STEAM_AUTHINVALID
    = "NETWORK_DISCONNECT_STEAM_AUTHINVALID"
  showEnum NETWORK_DISCONNECT_STEAM_VACBANSTATE
    = "NETWORK_DISCONNECT_STEAM_VACBANSTATE"
  showEnum NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE
    = "NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE"
  showEnum NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
    = "NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT"
  showEnum NETWORK_DISCONNECT_STEAM_DROPPED
    = "NETWORK_DISCONNECT_STEAM_DROPPED"
  showEnum NETWORK_DISCONNECT_STEAM_OWNERSHIP
    = "NETWORK_DISCONNECT_STEAM_OWNERSHIP"
  showEnum NETWORK_DISCONNECT_SERVERINFO_OVERFLOW
    = "NETWORK_DISCONNECT_SERVERINFO_OVERFLOW"
  showEnum NETWORK_DISCONNECT_TICKMSG_OVERFLOW
    = "NETWORK_DISCONNECT_TICKMSG_OVERFLOW"
  showEnum NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW
    = "NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW"
  showEnum NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW
    = "NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW"
  showEnum NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW
    = "NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW"
  showEnum NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW
    = "NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW"
  showEnum NETWORK_DISCONNECT_SNAPSHOTOVERFLOW
    = "NETWORK_DISCONNECT_SNAPSHOTOVERFLOW"
  showEnum NETWORK_DISCONNECT_SNAPSHOTERROR
    = "NETWORK_DISCONNECT_SNAPSHOTERROR"
  showEnum NETWORK_DISCONNECT_RELIABLEOVERFLOW
    = "NETWORK_DISCONNECT_RELIABLEOVERFLOW"
  showEnum NETWORK_DISCONNECT_BADDELTATICK
    = "NETWORK_DISCONNECT_BADDELTATICK"
  showEnum NETWORK_DISCONNECT_NOMORESPLITS
    = "NETWORK_DISCONNECT_NOMORESPLITS"
  showEnum NETWORK_DISCONNECT_TIMEDOUT
    = "NETWORK_DISCONNECT_TIMEDOUT"
  showEnum NETWORK_DISCONNECT_DISCONNECTED
    = "NETWORK_DISCONNECT_DISCONNECTED"
  showEnum NETWORK_DISCONNECT_LEAVINGSPLIT
    = "NETWORK_DISCONNECT_LEAVINGSPLIT"
  showEnum NETWORK_DISCONNECT_DIFFERENTCLASSTABLES
    = "NETWORK_DISCONNECT_DIFFERENTCLASSTABLES"
  showEnum NETWORK_DISCONNECT_BADRELAYPASSWORD
    = "NETWORK_DISCONNECT_BADRELAYPASSWORD"
  showEnum NETWORK_DISCONNECT_BADSPECTATORPASSWORD
    = "NETWORK_DISCONNECT_BADSPECTATORPASSWORD"
  showEnum NETWORK_DISCONNECT_HLTVRESTRICTED
    = "NETWORK_DISCONNECT_HLTVRESTRICTED"
  showEnum NETWORK_DISCONNECT_NOSPECTATORS
    = "NETWORK_DISCONNECT_NOSPECTATORS"
  showEnum NETWORK_DISCONNECT_HLTVUNAVAILABLE
    = "NETWORK_DISCONNECT_HLTVUNAVAILABLE"
  showEnum NETWORK_DISCONNECT_HLTVSTOP
    = "NETWORK_DISCONNECT_HLTVSTOP"
  showEnum NETWORK_DISCONNECT_KICKED = "NETWORK_DISCONNECT_KICKED"
  showEnum NETWORK_DISCONNECT_BANADDED
    = "NETWORK_DISCONNECT_BANADDED"
  showEnum NETWORK_DISCONNECT_KICKBANADDED
    = "NETWORK_DISCONNECT_KICKBANADDED"
  showEnum NETWORK_DISCONNECT_HLTVDIRECT
    = "NETWORK_DISCONNECT_HLTVDIRECT"
  showEnum NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA
    = "NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA"
  showEnum NETWORK_DISCONNECT_PURESERVER_MISMATCH
    = "NETWORK_DISCONNECT_PURESERVER_MISMATCH"
  showEnum NETWORK_DISCONNECT_USERCMD = "NETWORK_DISCONNECT_USERCMD"
  showEnum NETWORK_DISCONNECT_REJECTED_BY_GAME
    = "NETWORK_DISCONNECT_REJECTED_BY_GAME"
  showEnum NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR
    = "NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR"
  showEnum NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR
    = "NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR"
  showEnum NETWORK_DISCONNECT_BAD_SERVER_PASSWORD
    = "NETWORK_DISCONNECT_BAD_SERVER_PASSWORD"
  showEnum NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION
    = "NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION"
  showEnum NETWORK_DISCONNECT_CONNECTION_FAILURE
    = "NETWORK_DISCONNECT_CONNECTION_FAILURE"
  showEnum NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS
    = "NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS"
  showEnum NETWORK_DISCONNECT_RECONNECTION
    = "NETWORK_DISCONNECT_RECONNECTION"
  showEnum NETWORK_DISCONNECT_LOOPSHUTDOWN
    = "NETWORK_DISCONNECT_LOOPSHUTDOWN"
  showEnum NETWORK_DISCONNECT_LOOPDEACTIVATE
    = "NETWORK_DISCONNECT_LOOPDEACTIVATE"
  showEnum NETWORK_DISCONNECT_HOST_ENDGAME
    = "NETWORK_DISCONNECT_HOST_ENDGAME"
  showEnum NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE
    = "NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE"
  showEnum NETWORK_DISCONNECT_CREATE_SERVER_FAILED
    = "NETWORK_DISCONNECT_CREATE_SERVER_FAILED"
  showEnum NETWORK_DISCONNECT_EXITING = "NETWORK_DISCONNECT_EXITING"
  showEnum NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE
    = "NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE"
  showEnum NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY
    = "NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY"
  showEnum NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL
    = "NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL"
  showEnum NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP
    = "NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP"
  showEnum NETWORK_DISCONNECT_CLIENT_NO_MAP
    = "NETWORK_DISCONNECT_CLIENT_NO_MAP"
  showEnum NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP
    = "NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP"
  showEnum NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM
    = "NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM"
  showEnum NETWORK_DISCONNECT_STEAM_DENY_MISC
    = "NETWORK_DISCONNECT_STEAM_DENY_MISC"
  showEnum NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT
    = "NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT"
  showEnum NETWORK_DISCONNECT_SERVER_SHUTDOWN
    = "NETWORK_DISCONNECT_SERVER_SHUTDOWN"
  showEnum NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE
    = "NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE"
  showEnum NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
    = "NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT"
  showEnum NETWORK_DISCONNECT_SERVER_INCOMPATIBLE
    = "NETWORK_DISCONNECT_SERVER_INCOMPATIBLE"
  showEnum NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS
    = "NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS"
  showEnum NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
    = "NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY"
  showEnum NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG
    = "NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG"
  showEnum NETWORK_DISCONNECT_LOCALPROBLEM_OTHER
    = "NETWORK_DISCONNECT_LOCALPROBLEM_OTHER"
  showEnum NETWORK_DISCONNECT_REMOTE_TIMEOUT
    = "NETWORK_DISCONNECT_REMOTE_TIMEOUT"
  showEnum NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING
    = "NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING"
  showEnum NETWORK_DISCONNECT_REMOTE_OTHER
    = "NETWORK_DISCONNECT_REMOTE_OTHER"
  showEnum NETWORK_DISCONNECT_REMOTE_BADCRYPT
    = "NETWORK_DISCONNECT_REMOTE_BADCRYPT"
  showEnum NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED
    = "NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED"
  showEnum NETWORK_DISCONNECT_UNUSUAL = "NETWORK_DISCONNECT_UNUSUAL"
  showEnum NETWORK_DISCONNECT_INTERNAL_ERROR
    = "NETWORK_DISCONNECT_INTERNAL_ERROR"
  showEnum NETWORK_DISCONNECT_REJECT_BADCHALLENGE
    = "NETWORK_DISCONNECT_REJECT_BADCHALLENGE"
  showEnum NETWORK_DISCONNECT_REJECT_NOLOBBY
    = "NETWORK_DISCONNECT_REJECT_NOLOBBY"
  showEnum NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP
    = "NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP"
  showEnum NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER
    = "NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER"
  showEnum NETWORK_DISCONNECT_REJECT_HIDDEN_GAME
    = "NETWORK_DISCONNECT_REJECT_HIDDEN_GAME"
  showEnum NETWORK_DISCONNECT_REJECT_LANRESTRICT
    = "NETWORK_DISCONNECT_REJECT_LANRESTRICT"
  showEnum NETWORK_DISCONNECT_REJECT_BADPASSWORD
    = "NETWORK_DISCONNECT_REJECT_BADPASSWORD"
  showEnum NETWORK_DISCONNECT_REJECT_SERVERFULL
    = "NETWORK_DISCONNECT_REJECT_SERVERFULL"
  showEnum NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION
    = "NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION"
  showEnum NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL
    = "NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL"
  showEnum NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY
    = "NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY"
  showEnum NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY
    = "NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY"
  showEnum NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH
    = "NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH"
  showEnum NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
    = "NETWORK_DISCONNECT_REJECT_OLDPROTOCOL"
  showEnum NETWORK_DISCONNECT_REJECT_NEWPROTOCOL
    = "NETWORK_DISCONNECT_REJECT_NEWPROTOCOL"
  showEnum NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION
    = "NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION"
  showEnum NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN
    = "NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN"
  showEnum NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN
    = "NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN"
  showEnum NETWORK_DISCONNECT_REJECT_STEAM
    = "NETWORK_DISCONNECT_REJECT_STEAM"
  showEnum NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED
    = "NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED"
  showEnum NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID
    = "NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID"
  showEnum NETWORK_DISCONNECT_REJECT_BANNED
    = "NETWORK_DISCONNECT_REJECT_BANNED"
  showEnum NETWORK_DISCONNECT_KICKED_TEAMKILLING
    = "NETWORK_DISCONNECT_KICKED_TEAMKILLING"
  showEnum NETWORK_DISCONNECT_KICKED_TK_START
    = "NETWORK_DISCONNECT_KICKED_TK_START"
  showEnum NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT
    = "NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT"
  showEnum NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT
    = "NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT"
  showEnum NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN
    = "NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN"
  showEnum NETWORK_DISCONNECT_KICKED_TEAMHURTING
    = "NETWORK_DISCONNECT_KICKED_TEAMHURTING"
  showEnum NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING
    = "NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING"
  showEnum NETWORK_DISCONNECT_KICKED_VOTEDOFF
    = "NETWORK_DISCONNECT_KICKED_VOTEDOFF"
  showEnum NETWORK_DISCONNECT_KICKED_IDLE
    = "NETWORK_DISCONNECT_KICKED_IDLE"
  showEnum NETWORK_DISCONNECT_KICKED_SUICIDE
    = "NETWORK_DISCONNECT_KICKED_SUICIDE"
  showEnum NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN
    = "NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN"
  showEnum NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET
    = "NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET"
  showEnum NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION
    = "NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION"
  showEnum NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR
    = "NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR"
  showEnum NETWORK_DISCONNECT_KICKED_INSECURECLIENT
    = "NETWORK_DISCONNECT_KICKED_INSECURECLIENT"
  readEnum k
    | (Prelude.==) k "NETWORK_DISCONNECT_INVALID"
    = Prelude.Just NETWORK_DISCONNECT_INVALID
    | (Prelude.==) k "NETWORK_DISCONNECT_SHUTDOWN"
    = Prelude.Just NETWORK_DISCONNECT_SHUTDOWN
    | (Prelude.==) k "NETWORK_DISCONNECT_DISCONNECT_BY_USER"
    = Prelude.Just NETWORK_DISCONNECT_DISCONNECT_BY_USER
    | (Prelude.==) k "NETWORK_DISCONNECT_DISCONNECT_BY_SERVER"
    = Prelude.Just NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
    | (Prelude.==) k "NETWORK_DISCONNECT_LOST"
    = Prelude.Just NETWORK_DISCONNECT_LOST
    | (Prelude.==) k "NETWORK_DISCONNECT_OVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_OVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_BANNED"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_BANNED
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_INUSE"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_INUSE
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_TICKET"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_TICKET
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_LOGON"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_LOGON
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_AUTHCANCELLED"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_AUTHCANCELLED
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_AUTHINVALID"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_AUTHINVALID
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_VACBANSTATE"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_VACBANSTATE
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_DROPPED"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_DROPPED
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_OWNERSHIP"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_OWNERSHIP
    | (Prelude.==) k "NETWORK_DISCONNECT_SERVERINFO_OVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_SERVERINFO_OVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_TICKMSG_OVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_TICKMSG_OVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_SNAPSHOTOVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_SNAPSHOTOVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_SNAPSHOTERROR"
    = Prelude.Just NETWORK_DISCONNECT_SNAPSHOTERROR
    | (Prelude.==) k "NETWORK_DISCONNECT_RELIABLEOVERFLOW"
    = Prelude.Just NETWORK_DISCONNECT_RELIABLEOVERFLOW
    | (Prelude.==) k "NETWORK_DISCONNECT_BADDELTATICK"
    = Prelude.Just NETWORK_DISCONNECT_BADDELTATICK
    | (Prelude.==) k "NETWORK_DISCONNECT_NOMORESPLITS"
    = Prelude.Just NETWORK_DISCONNECT_NOMORESPLITS
    | (Prelude.==) k "NETWORK_DISCONNECT_TIMEDOUT"
    = Prelude.Just NETWORK_DISCONNECT_TIMEDOUT
    | (Prelude.==) k "NETWORK_DISCONNECT_DISCONNECTED"
    = Prelude.Just NETWORK_DISCONNECT_DISCONNECTED
    | (Prelude.==) k "NETWORK_DISCONNECT_LEAVINGSPLIT"
    = Prelude.Just NETWORK_DISCONNECT_LEAVINGSPLIT
    | (Prelude.==) k "NETWORK_DISCONNECT_DIFFERENTCLASSTABLES"
    = Prelude.Just NETWORK_DISCONNECT_DIFFERENTCLASSTABLES
    | (Prelude.==) k "NETWORK_DISCONNECT_BADRELAYPASSWORD"
    = Prelude.Just NETWORK_DISCONNECT_BADRELAYPASSWORD
    | (Prelude.==) k "NETWORK_DISCONNECT_BADSPECTATORPASSWORD"
    = Prelude.Just NETWORK_DISCONNECT_BADSPECTATORPASSWORD
    | (Prelude.==) k "NETWORK_DISCONNECT_HLTVRESTRICTED"
    = Prelude.Just NETWORK_DISCONNECT_HLTVRESTRICTED
    | (Prelude.==) k "NETWORK_DISCONNECT_NOSPECTATORS"
    = Prelude.Just NETWORK_DISCONNECT_NOSPECTATORS
    | (Prelude.==) k "NETWORK_DISCONNECT_HLTVUNAVAILABLE"
    = Prelude.Just NETWORK_DISCONNECT_HLTVUNAVAILABLE
    | (Prelude.==) k "NETWORK_DISCONNECT_HLTVSTOP"
    = Prelude.Just NETWORK_DISCONNECT_HLTVSTOP
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED"
    = Prelude.Just NETWORK_DISCONNECT_KICKED
    | (Prelude.==) k "NETWORK_DISCONNECT_BANADDED"
    = Prelude.Just NETWORK_DISCONNECT_BANADDED
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKBANADDED"
    = Prelude.Just NETWORK_DISCONNECT_KICKBANADDED
    | (Prelude.==) k "NETWORK_DISCONNECT_HLTVDIRECT"
    = Prelude.Just NETWORK_DISCONNECT_HLTVDIRECT
    | (Prelude.==) k "NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA"
    = Prelude.Just NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA
    | (Prelude.==) k "NETWORK_DISCONNECT_PURESERVER_MISMATCH"
    = Prelude.Just NETWORK_DISCONNECT_PURESERVER_MISMATCH
    | (Prelude.==) k "NETWORK_DISCONNECT_USERCMD"
    = Prelude.Just NETWORK_DISCONNECT_USERCMD
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECTED_BY_GAME"
    = Prelude.Just NETWORK_DISCONNECT_REJECTED_BY_GAME
    | (Prelude.==) k "NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR"
    = Prelude.Just NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR
    | (Prelude.==) k "NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR"
    = Prelude.Just NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR
    | (Prelude.==) k "NETWORK_DISCONNECT_BAD_SERVER_PASSWORD"
    = Prelude.Just NETWORK_DISCONNECT_BAD_SERVER_PASSWORD
    | (Prelude.==) k "NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION"
    = Prelude.Just NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION
    | (Prelude.==) k "NETWORK_DISCONNECT_CONNECTION_FAILURE"
    = Prelude.Just NETWORK_DISCONNECT_CONNECTION_FAILURE
    | (Prelude.==) k "NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS"
    = Prelude.Just NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS
    | (Prelude.==) k "NETWORK_DISCONNECT_RECONNECTION"
    = Prelude.Just NETWORK_DISCONNECT_RECONNECTION
    | (Prelude.==) k "NETWORK_DISCONNECT_LOOPSHUTDOWN"
    = Prelude.Just NETWORK_DISCONNECT_LOOPSHUTDOWN
    | (Prelude.==) k "NETWORK_DISCONNECT_LOOPDEACTIVATE"
    = Prelude.Just NETWORK_DISCONNECT_LOOPDEACTIVATE
    | (Prelude.==) k "NETWORK_DISCONNECT_HOST_ENDGAME"
    = Prelude.Just NETWORK_DISCONNECT_HOST_ENDGAME
    | (Prelude.==) k "NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE"
    = Prelude.Just NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE
    | (Prelude.==) k "NETWORK_DISCONNECT_CREATE_SERVER_FAILED"
    = Prelude.Just NETWORK_DISCONNECT_CREATE_SERVER_FAILED
    | (Prelude.==) k "NETWORK_DISCONNECT_EXITING"
    = Prelude.Just NETWORK_DISCONNECT_EXITING
    | (Prelude.==) k "NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE"
    = Prelude.Just NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE
    | (Prelude.==) k "NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY"
    = Prelude.Just NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY
    | (Prelude.==) k "NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL"
    = Prelude.Just NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL
    | (Prelude.==) k "NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP"
    = Prelude.Just NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP
    | (Prelude.==) k "NETWORK_DISCONNECT_CLIENT_NO_MAP"
    = Prelude.Just NETWORK_DISCONNECT_CLIENT_NO_MAP
    | (Prelude.==) k "NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP"
    = Prelude.Just NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP
    | (Prelude.==) k "NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM"
    = Prelude.Just NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_DENY_MISC"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_DENY_MISC
    | (Prelude.==) k "NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT"
    = Prelude.Just NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT
    | (Prelude.==) k "NETWORK_DISCONNECT_SERVER_SHUTDOWN"
    = Prelude.Just NETWORK_DISCONNECT_SERVER_SHUTDOWN
    | (Prelude.==) k "NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE"
    = Prelude.Just NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE
    | (Prelude.==) k "NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT"
    = Prelude.Just NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
    | (Prelude.==) k "NETWORK_DISCONNECT_SERVER_INCOMPATIBLE"
    = Prelude.Just NETWORK_DISCONNECT_SERVER_INCOMPATIBLE
    | (Prelude.==) k "NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS"
    = Prelude.Just NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS
    | (Prelude.==)
        k "NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY"
    = Prelude.Just
        NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
    | (Prelude.==) k "NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG"
    = Prelude.Just NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG
    | (Prelude.==) k "NETWORK_DISCONNECT_LOCALPROBLEM_OTHER"
    = Prelude.Just NETWORK_DISCONNECT_LOCALPROBLEM_OTHER
    | (Prelude.==) k "NETWORK_DISCONNECT_REMOTE_TIMEOUT"
    = Prelude.Just NETWORK_DISCONNECT_REMOTE_TIMEOUT
    | (Prelude.==) k "NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING"
    = Prelude.Just NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING
    | (Prelude.==) k "NETWORK_DISCONNECT_REMOTE_OTHER"
    = Prelude.Just NETWORK_DISCONNECT_REMOTE_OTHER
    | (Prelude.==) k "NETWORK_DISCONNECT_REMOTE_BADCRYPT"
    = Prelude.Just NETWORK_DISCONNECT_REMOTE_BADCRYPT
    | (Prelude.==) k "NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED"
    = Prelude.Just NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED
    | (Prelude.==) k "NETWORK_DISCONNECT_UNUSUAL"
    = Prelude.Just NETWORK_DISCONNECT_UNUSUAL
    | (Prelude.==) k "NETWORK_DISCONNECT_INTERNAL_ERROR"
    = Prelude.Just NETWORK_DISCONNECT_INTERNAL_ERROR
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_BADCHALLENGE"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_BADCHALLENGE
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_NOLOBBY"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_NOLOBBY
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_HIDDEN_GAME"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_HIDDEN_GAME
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_LANRESTRICT"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_LANRESTRICT
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_BADPASSWORD"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_BADPASSWORD
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_SERVERFULL"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_SERVERFULL
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_OLDPROTOCOL"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_NEWPROTOCOL"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_NEWPROTOCOL
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_STEAM"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_STEAM
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID
    | (Prelude.==) k "NETWORK_DISCONNECT_REJECT_BANNED"
    = Prelude.Just NETWORK_DISCONNECT_REJECT_BANNED
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_TEAMKILLING"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_TEAMKILLING
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_TK_START"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_TK_START
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_TEAMHURTING"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_TEAMHURTING
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_VOTEDOFF"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_VOTEDOFF
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_IDLE"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_IDLE
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_SUICIDE"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_SUICIDE
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR
    | (Prelude.==) k "NETWORK_DISCONNECT_KICKED_INSECURECLIENT"
    = Prelude.Just NETWORK_DISCONNECT_KICKED_INSECURECLIENT
    | Prelude.otherwise
    = (Prelude.>>=) (Text.Read.readMaybe k) Data.ProtoLens.maybeToEnum
instance Prelude.Bounded ENetworkDisconnectionReason where
  minBound = NETWORK_DISCONNECT_INVALID
  maxBound = NETWORK_DISCONNECT_KICKED_INSECURECLIENT
instance Prelude.Enum ENetworkDisconnectionReason where
  toEnum k__
    = Prelude.maybe
        (Prelude.error
           ((Prelude.++)
              "toEnum: unknown value for enum ENetworkDisconnectionReason: "
              (Prelude.show k__)))
        Prelude.id (Data.ProtoLens.maybeToEnum k__)
  fromEnum NETWORK_DISCONNECT_INVALID = 0
  fromEnum NETWORK_DISCONNECT_SHUTDOWN = 1
  fromEnum NETWORK_DISCONNECT_DISCONNECT_BY_USER = 2
  fromEnum NETWORK_DISCONNECT_DISCONNECT_BY_SERVER = 3
  fromEnum NETWORK_DISCONNECT_LOST = 4
  fromEnum NETWORK_DISCONNECT_OVERFLOW = 5
  fromEnum NETWORK_DISCONNECT_STEAM_BANNED = 6
  fromEnum NETWORK_DISCONNECT_STEAM_INUSE = 7
  fromEnum NETWORK_DISCONNECT_STEAM_TICKET = 8
  fromEnum NETWORK_DISCONNECT_STEAM_LOGON = 9
  fromEnum NETWORK_DISCONNECT_STEAM_AUTHCANCELLED = 10
  fromEnum NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED = 11
  fromEnum NETWORK_DISCONNECT_STEAM_AUTHINVALID = 12
  fromEnum NETWORK_DISCONNECT_STEAM_VACBANSTATE = 13
  fromEnum NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE = 14
  fromEnum NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT = 15
  fromEnum NETWORK_DISCONNECT_STEAM_DROPPED = 16
  fromEnum NETWORK_DISCONNECT_STEAM_OWNERSHIP = 17
  fromEnum NETWORK_DISCONNECT_SERVERINFO_OVERFLOW = 18
  fromEnum NETWORK_DISCONNECT_TICKMSG_OVERFLOW = 19
  fromEnum NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW = 20
  fromEnum NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW = 21
  fromEnum NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW = 22
  fromEnum NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW = 23
  fromEnum NETWORK_DISCONNECT_SNAPSHOTOVERFLOW = 24
  fromEnum NETWORK_DISCONNECT_SNAPSHOTERROR = 25
  fromEnum NETWORK_DISCONNECT_RELIABLEOVERFLOW = 26
  fromEnum NETWORK_DISCONNECT_BADDELTATICK = 27
  fromEnum NETWORK_DISCONNECT_NOMORESPLITS = 28
  fromEnum NETWORK_DISCONNECT_TIMEDOUT = 29
  fromEnum NETWORK_DISCONNECT_DISCONNECTED = 30
  fromEnum NETWORK_DISCONNECT_LEAVINGSPLIT = 31
  fromEnum NETWORK_DISCONNECT_DIFFERENTCLASSTABLES = 32
  fromEnum NETWORK_DISCONNECT_BADRELAYPASSWORD = 33
  fromEnum NETWORK_DISCONNECT_BADSPECTATORPASSWORD = 34
  fromEnum NETWORK_DISCONNECT_HLTVRESTRICTED = 35
  fromEnum NETWORK_DISCONNECT_NOSPECTATORS = 36
  fromEnum NETWORK_DISCONNECT_HLTVUNAVAILABLE = 37
  fromEnum NETWORK_DISCONNECT_HLTVSTOP = 38
  fromEnum NETWORK_DISCONNECT_KICKED = 39
  fromEnum NETWORK_DISCONNECT_BANADDED = 40
  fromEnum NETWORK_DISCONNECT_KICKBANADDED = 41
  fromEnum NETWORK_DISCONNECT_HLTVDIRECT = 42
  fromEnum NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA = 43
  fromEnum NETWORK_DISCONNECT_PURESERVER_MISMATCH = 44
  fromEnum NETWORK_DISCONNECT_USERCMD = 45
  fromEnum NETWORK_DISCONNECT_REJECTED_BY_GAME = 46
  fromEnum NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR = 47
  fromEnum NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR = 48
  fromEnum NETWORK_DISCONNECT_BAD_SERVER_PASSWORD = 49
  fromEnum NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION = 50
  fromEnum NETWORK_DISCONNECT_CONNECTION_FAILURE = 51
  fromEnum NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS = 52
  fromEnum NETWORK_DISCONNECT_RECONNECTION = 53
  fromEnum NETWORK_DISCONNECT_LOOPSHUTDOWN = 54
  fromEnum NETWORK_DISCONNECT_LOOPDEACTIVATE = 55
  fromEnum NETWORK_DISCONNECT_HOST_ENDGAME = 56
  fromEnum NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE = 57
  fromEnum NETWORK_DISCONNECT_CREATE_SERVER_FAILED = 58
  fromEnum NETWORK_DISCONNECT_EXITING = 59
  fromEnum NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE = 60
  fromEnum NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY = 61
  fromEnum NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL = 62
  fromEnum NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP = 63
  fromEnum NETWORK_DISCONNECT_CLIENT_NO_MAP = 64
  fromEnum NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP = 65
  fromEnum NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM = 66
  fromEnum NETWORK_DISCONNECT_STEAM_DENY_MISC = 67
  fromEnum NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT = 68
  fromEnum NETWORK_DISCONNECT_SERVER_SHUTDOWN = 69
  fromEnum NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE = 71
  fromEnum NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT = 72
  fromEnum NETWORK_DISCONNECT_SERVER_INCOMPATIBLE = 73
  fromEnum NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS = 74
  fromEnum NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
    = 75
  fromEnum NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG = 76
  fromEnum NETWORK_DISCONNECT_LOCALPROBLEM_OTHER = 77
  fromEnum NETWORK_DISCONNECT_REMOTE_TIMEOUT = 79
  fromEnum NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING = 80
  fromEnum NETWORK_DISCONNECT_REMOTE_OTHER = 81
  fromEnum NETWORK_DISCONNECT_REMOTE_BADCRYPT = 82
  fromEnum NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED = 83
  fromEnum NETWORK_DISCONNECT_UNUSUAL = 84
  fromEnum NETWORK_DISCONNECT_INTERNAL_ERROR = 85
  fromEnum NETWORK_DISCONNECT_REJECT_BADCHALLENGE = 128
  fromEnum NETWORK_DISCONNECT_REJECT_NOLOBBY = 129
  fromEnum NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP = 130
  fromEnum NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER = 131
  fromEnum NETWORK_DISCONNECT_REJECT_HIDDEN_GAME = 132
  fromEnum NETWORK_DISCONNECT_REJECT_LANRESTRICT = 133
  fromEnum NETWORK_DISCONNECT_REJECT_BADPASSWORD = 134
  fromEnum NETWORK_DISCONNECT_REJECT_SERVERFULL = 135
  fromEnum NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION = 136
  fromEnum NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL = 137
  fromEnum NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY = 138
  fromEnum NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY = 139
  fromEnum NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH = 140
  fromEnum NETWORK_DISCONNECT_REJECT_OLDPROTOCOL = 141
  fromEnum NETWORK_DISCONNECT_REJECT_NEWPROTOCOL = 142
  fromEnum NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION = 143
  fromEnum NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN = 144
  fromEnum NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN = 145
  fromEnum NETWORK_DISCONNECT_REJECT_STEAM = 146
  fromEnum NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED = 147
  fromEnum NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID = 148
  fromEnum NETWORK_DISCONNECT_REJECT_BANNED = 149
  fromEnum NETWORK_DISCONNECT_KICKED_TEAMKILLING = 150
  fromEnum NETWORK_DISCONNECT_KICKED_TK_START = 151
  fromEnum NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT = 152
  fromEnum NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT = 153
  fromEnum NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN = 154
  fromEnum NETWORK_DISCONNECT_KICKED_TEAMHURTING = 155
  fromEnum NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING = 156
  fromEnum NETWORK_DISCONNECT_KICKED_VOTEDOFF = 157
  fromEnum NETWORK_DISCONNECT_KICKED_IDLE = 158
  fromEnum NETWORK_DISCONNECT_KICKED_SUICIDE = 159
  fromEnum NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN = 160
  fromEnum NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET = 161
  fromEnum NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION = 162
  fromEnum NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR = 163
  fromEnum NETWORK_DISCONNECT_KICKED_INSECURECLIENT = 164
  succ NETWORK_DISCONNECT_KICKED_INSECURECLIENT
    = Prelude.error
        "ENetworkDisconnectionReason.succ: bad argument NETWORK_DISCONNECT_KICKED_INSECURECLIENT. This value would be out of bounds."
  succ NETWORK_DISCONNECT_INVALID = NETWORK_DISCONNECT_SHUTDOWN
  succ NETWORK_DISCONNECT_SHUTDOWN
    = NETWORK_DISCONNECT_DISCONNECT_BY_USER
  succ NETWORK_DISCONNECT_DISCONNECT_BY_USER
    = NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
  succ NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
    = NETWORK_DISCONNECT_LOST
  succ NETWORK_DISCONNECT_LOST = NETWORK_DISCONNECT_OVERFLOW
  succ NETWORK_DISCONNECT_OVERFLOW = NETWORK_DISCONNECT_STEAM_BANNED
  succ NETWORK_DISCONNECT_STEAM_BANNED
    = NETWORK_DISCONNECT_STEAM_INUSE
  succ NETWORK_DISCONNECT_STEAM_INUSE
    = NETWORK_DISCONNECT_STEAM_TICKET
  succ NETWORK_DISCONNECT_STEAM_TICKET
    = NETWORK_DISCONNECT_STEAM_LOGON
  succ NETWORK_DISCONNECT_STEAM_LOGON
    = NETWORK_DISCONNECT_STEAM_AUTHCANCELLED
  succ NETWORK_DISCONNECT_STEAM_AUTHCANCELLED
    = NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED
  succ NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED
    = NETWORK_DISCONNECT_STEAM_AUTHINVALID
  succ NETWORK_DISCONNECT_STEAM_AUTHINVALID
    = NETWORK_DISCONNECT_STEAM_VACBANSTATE
  succ NETWORK_DISCONNECT_STEAM_VACBANSTATE
    = NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE
  succ NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE
    = NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
  succ NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
    = NETWORK_DISCONNECT_STEAM_DROPPED
  succ NETWORK_DISCONNECT_STEAM_DROPPED
    = NETWORK_DISCONNECT_STEAM_OWNERSHIP
  succ NETWORK_DISCONNECT_STEAM_OWNERSHIP
    = NETWORK_DISCONNECT_SERVERINFO_OVERFLOW
  succ NETWORK_DISCONNECT_SERVERINFO_OVERFLOW
    = NETWORK_DISCONNECT_TICKMSG_OVERFLOW
  succ NETWORK_DISCONNECT_TICKMSG_OVERFLOW
    = NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW
  succ NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW
    = NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW
  succ NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW
    = NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW
  succ NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW
    = NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW
  succ NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW
    = NETWORK_DISCONNECT_SNAPSHOTOVERFLOW
  succ NETWORK_DISCONNECT_SNAPSHOTOVERFLOW
    = NETWORK_DISCONNECT_SNAPSHOTERROR
  succ NETWORK_DISCONNECT_SNAPSHOTERROR
    = NETWORK_DISCONNECT_RELIABLEOVERFLOW
  succ NETWORK_DISCONNECT_RELIABLEOVERFLOW
    = NETWORK_DISCONNECT_BADDELTATICK
  succ NETWORK_DISCONNECT_BADDELTATICK
    = NETWORK_DISCONNECT_NOMORESPLITS
  succ NETWORK_DISCONNECT_NOMORESPLITS = NETWORK_DISCONNECT_TIMEDOUT
  succ NETWORK_DISCONNECT_TIMEDOUT = NETWORK_DISCONNECT_DISCONNECTED
  succ NETWORK_DISCONNECT_DISCONNECTED
    = NETWORK_DISCONNECT_LEAVINGSPLIT
  succ NETWORK_DISCONNECT_LEAVINGSPLIT
    = NETWORK_DISCONNECT_DIFFERENTCLASSTABLES
  succ NETWORK_DISCONNECT_DIFFERENTCLASSTABLES
    = NETWORK_DISCONNECT_BADRELAYPASSWORD
  succ NETWORK_DISCONNECT_BADRELAYPASSWORD
    = NETWORK_DISCONNECT_BADSPECTATORPASSWORD
  succ NETWORK_DISCONNECT_BADSPECTATORPASSWORD
    = NETWORK_DISCONNECT_HLTVRESTRICTED
  succ NETWORK_DISCONNECT_HLTVRESTRICTED
    = NETWORK_DISCONNECT_NOSPECTATORS
  succ NETWORK_DISCONNECT_NOSPECTATORS
    = NETWORK_DISCONNECT_HLTVUNAVAILABLE
  succ NETWORK_DISCONNECT_HLTVUNAVAILABLE
    = NETWORK_DISCONNECT_HLTVSTOP
  succ NETWORK_DISCONNECT_HLTVSTOP = NETWORK_DISCONNECT_KICKED
  succ NETWORK_DISCONNECT_KICKED = NETWORK_DISCONNECT_BANADDED
  succ NETWORK_DISCONNECT_BANADDED = NETWORK_DISCONNECT_KICKBANADDED
  succ NETWORK_DISCONNECT_KICKBANADDED
    = NETWORK_DISCONNECT_HLTVDIRECT
  succ NETWORK_DISCONNECT_HLTVDIRECT
    = NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA
  succ NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA
    = NETWORK_DISCONNECT_PURESERVER_MISMATCH
  succ NETWORK_DISCONNECT_PURESERVER_MISMATCH
    = NETWORK_DISCONNECT_USERCMD
  succ NETWORK_DISCONNECT_USERCMD
    = NETWORK_DISCONNECT_REJECTED_BY_GAME
  succ NETWORK_DISCONNECT_REJECTED_BY_GAME
    = NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR
  succ NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR
    = NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR
  succ NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR
    = NETWORK_DISCONNECT_BAD_SERVER_PASSWORD
  succ NETWORK_DISCONNECT_BAD_SERVER_PASSWORD
    = NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION
  succ NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION
    = NETWORK_DISCONNECT_CONNECTION_FAILURE
  succ NETWORK_DISCONNECT_CONNECTION_FAILURE
    = NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS
  succ NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS
    = NETWORK_DISCONNECT_RECONNECTION
  succ NETWORK_DISCONNECT_RECONNECTION
    = NETWORK_DISCONNECT_LOOPSHUTDOWN
  succ NETWORK_DISCONNECT_LOOPSHUTDOWN
    = NETWORK_DISCONNECT_LOOPDEACTIVATE
  succ NETWORK_DISCONNECT_LOOPDEACTIVATE
    = NETWORK_DISCONNECT_HOST_ENDGAME
  succ NETWORK_DISCONNECT_HOST_ENDGAME
    = NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE
  succ NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE
    = NETWORK_DISCONNECT_CREATE_SERVER_FAILED
  succ NETWORK_DISCONNECT_CREATE_SERVER_FAILED
    = NETWORK_DISCONNECT_EXITING
  succ NETWORK_DISCONNECT_EXITING
    = NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE
  succ NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE
    = NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY
  succ NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY
    = NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL
  succ NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL
    = NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP
  succ NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP
    = NETWORK_DISCONNECT_CLIENT_NO_MAP
  succ NETWORK_DISCONNECT_CLIENT_NO_MAP
    = NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP
  succ NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP
    = NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM
  succ NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM
    = NETWORK_DISCONNECT_STEAM_DENY_MISC
  succ NETWORK_DISCONNECT_STEAM_DENY_MISC
    = NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT
  succ NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT
    = NETWORK_DISCONNECT_SERVER_SHUTDOWN
  succ NETWORK_DISCONNECT_SERVER_SHUTDOWN
    = NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE
  succ NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE
    = NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
  succ NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
    = NETWORK_DISCONNECT_SERVER_INCOMPATIBLE
  succ NETWORK_DISCONNECT_SERVER_INCOMPATIBLE
    = NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS
  succ NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS
    = NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
  succ NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
    = NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG
  succ NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG
    = NETWORK_DISCONNECT_LOCALPROBLEM_OTHER
  succ NETWORK_DISCONNECT_LOCALPROBLEM_OTHER
    = NETWORK_DISCONNECT_REMOTE_TIMEOUT
  succ NETWORK_DISCONNECT_REMOTE_TIMEOUT
    = NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING
  succ NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING
    = NETWORK_DISCONNECT_REMOTE_OTHER
  succ NETWORK_DISCONNECT_REMOTE_OTHER
    = NETWORK_DISCONNECT_REMOTE_BADCRYPT
  succ NETWORK_DISCONNECT_REMOTE_BADCRYPT
    = NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED
  succ NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED
    = NETWORK_DISCONNECT_UNUSUAL
  succ NETWORK_DISCONNECT_UNUSUAL = NETWORK_DISCONNECT_INTERNAL_ERROR
  succ NETWORK_DISCONNECT_INTERNAL_ERROR
    = NETWORK_DISCONNECT_REJECT_BADCHALLENGE
  succ NETWORK_DISCONNECT_REJECT_BADCHALLENGE
    = NETWORK_DISCONNECT_REJECT_NOLOBBY
  succ NETWORK_DISCONNECT_REJECT_NOLOBBY
    = NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP
  succ NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP
    = NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER
  succ NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER
    = NETWORK_DISCONNECT_REJECT_HIDDEN_GAME
  succ NETWORK_DISCONNECT_REJECT_HIDDEN_GAME
    = NETWORK_DISCONNECT_REJECT_LANRESTRICT
  succ NETWORK_DISCONNECT_REJECT_LANRESTRICT
    = NETWORK_DISCONNECT_REJECT_BADPASSWORD
  succ NETWORK_DISCONNECT_REJECT_BADPASSWORD
    = NETWORK_DISCONNECT_REJECT_SERVERFULL
  succ NETWORK_DISCONNECT_REJECT_SERVERFULL
    = NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION
  succ NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION
    = NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL
  succ NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL
    = NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY
  succ NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY
    = NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY
  succ NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY
    = NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH
  succ NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH
    = NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
  succ NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
    = NETWORK_DISCONNECT_REJECT_NEWPROTOCOL
  succ NETWORK_DISCONNECT_REJECT_NEWPROTOCOL
    = NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION
  succ NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION
    = NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN
  succ NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN
    = NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN
  succ NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN
    = NETWORK_DISCONNECT_REJECT_STEAM
  succ NETWORK_DISCONNECT_REJECT_STEAM
    = NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED
  succ NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED
    = NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID
  succ NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID
    = NETWORK_DISCONNECT_REJECT_BANNED
  succ NETWORK_DISCONNECT_REJECT_BANNED
    = NETWORK_DISCONNECT_KICKED_TEAMKILLING
  succ NETWORK_DISCONNECT_KICKED_TEAMKILLING
    = NETWORK_DISCONNECT_KICKED_TK_START
  succ NETWORK_DISCONNECT_KICKED_TK_START
    = NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT
  succ NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT
    = NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT
  succ NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT
    = NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN
  succ NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN
    = NETWORK_DISCONNECT_KICKED_TEAMHURTING
  succ NETWORK_DISCONNECT_KICKED_TEAMHURTING
    = NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING
  succ NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING
    = NETWORK_DISCONNECT_KICKED_VOTEDOFF
  succ NETWORK_DISCONNECT_KICKED_VOTEDOFF
    = NETWORK_DISCONNECT_KICKED_IDLE
  succ NETWORK_DISCONNECT_KICKED_IDLE
    = NETWORK_DISCONNECT_KICKED_SUICIDE
  succ NETWORK_DISCONNECT_KICKED_SUICIDE
    = NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN
  succ NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN
    = NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET
  succ NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET
    = NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION
  succ NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION
    = NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR
  succ NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR
    = NETWORK_DISCONNECT_KICKED_INSECURECLIENT
  pred NETWORK_DISCONNECT_INVALID
    = Prelude.error
        "ENetworkDisconnectionReason.pred: bad argument NETWORK_DISCONNECT_INVALID. This value would be out of bounds."
  pred NETWORK_DISCONNECT_SHUTDOWN = NETWORK_DISCONNECT_INVALID
  pred NETWORK_DISCONNECT_DISCONNECT_BY_USER
    = NETWORK_DISCONNECT_SHUTDOWN
  pred NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
    = NETWORK_DISCONNECT_DISCONNECT_BY_USER
  pred NETWORK_DISCONNECT_LOST
    = NETWORK_DISCONNECT_DISCONNECT_BY_SERVER
  pred NETWORK_DISCONNECT_OVERFLOW = NETWORK_DISCONNECT_LOST
  pred NETWORK_DISCONNECT_STEAM_BANNED = NETWORK_DISCONNECT_OVERFLOW
  pred NETWORK_DISCONNECT_STEAM_INUSE
    = NETWORK_DISCONNECT_STEAM_BANNED
  pred NETWORK_DISCONNECT_STEAM_TICKET
    = NETWORK_DISCONNECT_STEAM_INUSE
  pred NETWORK_DISCONNECT_STEAM_LOGON
    = NETWORK_DISCONNECT_STEAM_TICKET
  pred NETWORK_DISCONNECT_STEAM_AUTHCANCELLED
    = NETWORK_DISCONNECT_STEAM_LOGON
  pred NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED
    = NETWORK_DISCONNECT_STEAM_AUTHCANCELLED
  pred NETWORK_DISCONNECT_STEAM_AUTHINVALID
    = NETWORK_DISCONNECT_STEAM_AUTHALREADYUSED
  pred NETWORK_DISCONNECT_STEAM_VACBANSTATE
    = NETWORK_DISCONNECT_STEAM_AUTHINVALID
  pred NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE
    = NETWORK_DISCONNECT_STEAM_VACBANSTATE
  pred NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
    = NETWORK_DISCONNECT_STEAM_LOGGED_IN_ELSEWHERE
  pred NETWORK_DISCONNECT_STEAM_DROPPED
    = NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
  pred NETWORK_DISCONNECT_STEAM_OWNERSHIP
    = NETWORK_DISCONNECT_STEAM_DROPPED
  pred NETWORK_DISCONNECT_SERVERINFO_OVERFLOW
    = NETWORK_DISCONNECT_STEAM_OWNERSHIP
  pred NETWORK_DISCONNECT_TICKMSG_OVERFLOW
    = NETWORK_DISCONNECT_SERVERINFO_OVERFLOW
  pred NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW
    = NETWORK_DISCONNECT_TICKMSG_OVERFLOW
  pred NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW
    = NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW
  pred NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW
    = NETWORK_DISCONNECT_DELTAENTMSG_OVERFLOW
  pred NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW
    = NETWORK_DISCONNECT_TEMPENTMSG_OVERFLOW
  pred NETWORK_DISCONNECT_SNAPSHOTOVERFLOW
    = NETWORK_DISCONNECT_SOUNDSMSG_OVERFLOW
  pred NETWORK_DISCONNECT_SNAPSHOTERROR
    = NETWORK_DISCONNECT_SNAPSHOTOVERFLOW
  pred NETWORK_DISCONNECT_RELIABLEOVERFLOW
    = NETWORK_DISCONNECT_SNAPSHOTERROR
  pred NETWORK_DISCONNECT_BADDELTATICK
    = NETWORK_DISCONNECT_RELIABLEOVERFLOW
  pred NETWORK_DISCONNECT_NOMORESPLITS
    = NETWORK_DISCONNECT_BADDELTATICK
  pred NETWORK_DISCONNECT_TIMEDOUT = NETWORK_DISCONNECT_NOMORESPLITS
  pred NETWORK_DISCONNECT_DISCONNECTED = NETWORK_DISCONNECT_TIMEDOUT
  pred NETWORK_DISCONNECT_LEAVINGSPLIT
    = NETWORK_DISCONNECT_DISCONNECTED
  pred NETWORK_DISCONNECT_DIFFERENTCLASSTABLES
    = NETWORK_DISCONNECT_LEAVINGSPLIT
  pred NETWORK_DISCONNECT_BADRELAYPASSWORD
    = NETWORK_DISCONNECT_DIFFERENTCLASSTABLES
  pred NETWORK_DISCONNECT_BADSPECTATORPASSWORD
    = NETWORK_DISCONNECT_BADRELAYPASSWORD
  pred NETWORK_DISCONNECT_HLTVRESTRICTED
    = NETWORK_DISCONNECT_BADSPECTATORPASSWORD
  pred NETWORK_DISCONNECT_NOSPECTATORS
    = NETWORK_DISCONNECT_HLTVRESTRICTED
  pred NETWORK_DISCONNECT_HLTVUNAVAILABLE
    = NETWORK_DISCONNECT_NOSPECTATORS
  pred NETWORK_DISCONNECT_HLTVSTOP
    = NETWORK_DISCONNECT_HLTVUNAVAILABLE
  pred NETWORK_DISCONNECT_KICKED = NETWORK_DISCONNECT_HLTVSTOP
  pred NETWORK_DISCONNECT_BANADDED = NETWORK_DISCONNECT_KICKED
  pred NETWORK_DISCONNECT_KICKBANADDED = NETWORK_DISCONNECT_BANADDED
  pred NETWORK_DISCONNECT_HLTVDIRECT
    = NETWORK_DISCONNECT_KICKBANADDED
  pred NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA
    = NETWORK_DISCONNECT_HLTVDIRECT
  pred NETWORK_DISCONNECT_PURESERVER_MISMATCH
    = NETWORK_DISCONNECT_PURESERVER_CLIENTEXTRA
  pred NETWORK_DISCONNECT_USERCMD
    = NETWORK_DISCONNECT_PURESERVER_MISMATCH
  pred NETWORK_DISCONNECT_REJECTED_BY_GAME
    = NETWORK_DISCONNECT_USERCMD
  pred NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR
    = NETWORK_DISCONNECT_REJECTED_BY_GAME
  pred NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR
    = NETWORK_DISCONNECT_MESSAGE_PARSE_ERROR
  pred NETWORK_DISCONNECT_BAD_SERVER_PASSWORD
    = NETWORK_DISCONNECT_INVALID_MESSAGE_ERROR
  pred NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION
    = NETWORK_DISCONNECT_BAD_SERVER_PASSWORD
  pred NETWORK_DISCONNECT_CONNECTION_FAILURE
    = NETWORK_DISCONNECT_DIRECT_CONNECT_RESERVATION
  pred NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS
    = NETWORK_DISCONNECT_CONNECTION_FAILURE
  pred NETWORK_DISCONNECT_RECONNECTION
    = NETWORK_DISCONNECT_NO_PEER_GROUP_HANDLERS
  pred NETWORK_DISCONNECT_LOOPSHUTDOWN
    = NETWORK_DISCONNECT_RECONNECTION
  pred NETWORK_DISCONNECT_LOOPDEACTIVATE
    = NETWORK_DISCONNECT_LOOPSHUTDOWN
  pred NETWORK_DISCONNECT_HOST_ENDGAME
    = NETWORK_DISCONNECT_LOOPDEACTIVATE
  pred NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE
    = NETWORK_DISCONNECT_HOST_ENDGAME
  pred NETWORK_DISCONNECT_CREATE_SERVER_FAILED
    = NETWORK_DISCONNECT_LOOP_LEVELLOAD_ACTIVATE
  pred NETWORK_DISCONNECT_EXITING
    = NETWORK_DISCONNECT_CREATE_SERVER_FAILED
  pred NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE
    = NETWORK_DISCONNECT_EXITING
  pred NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY
    = NETWORK_DISCONNECT_REQUEST_HOSTSTATE_IDLE
  pred NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL
    = NETWORK_DISCONNECT_REQUEST_HOSTSTATE_HLTVRELAY
  pred NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP
    = NETWORK_DISCONNECT_CLIENT_CONSISTENCY_FAIL
  pred NETWORK_DISCONNECT_CLIENT_NO_MAP
    = NETWORK_DISCONNECT_CLIENT_UNABLE_TO_CRC_MAP
  pred NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP
    = NETWORK_DISCONNECT_CLIENT_NO_MAP
  pred NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM
    = NETWORK_DISCONNECT_CLIENT_DIFFERENT_MAP
  pred NETWORK_DISCONNECT_STEAM_DENY_MISC
    = NETWORK_DISCONNECT_SERVER_REQUIRES_STEAM
  pred NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT
    = NETWORK_DISCONNECT_STEAM_DENY_MISC
  pred NETWORK_DISCONNECT_SERVER_SHUTDOWN
    = NETWORK_DISCONNECT_STEAM_DENY_BAD_ANTI_CHEAT
  pred NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE
    = NETWORK_DISCONNECT_SERVER_SHUTDOWN
  pred NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
    = NETWORK_DISCONNECT_REPLAY_INCOMPATIBLE
  pred NETWORK_DISCONNECT_SERVER_INCOMPATIBLE
    = NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
  pred NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS
    = NETWORK_DISCONNECT_SERVER_INCOMPATIBLE
  pred NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
    = NETWORK_DISCONNECT_LOCALPROBLEM_MANYRELAYS
  pred NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG
    = NETWORK_DISCONNECT_LOCALPROBLEM_HOSTEDSERVERPRIMARYRELAY
  pred NETWORK_DISCONNECT_LOCALPROBLEM_OTHER
    = NETWORK_DISCONNECT_LOCALPROBLEM_NETWORKCONFIG
  pred NETWORK_DISCONNECT_REMOTE_TIMEOUT
    = NETWORK_DISCONNECT_LOCALPROBLEM_OTHER
  pred NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING
    = NETWORK_DISCONNECT_REMOTE_TIMEOUT
  pred NETWORK_DISCONNECT_REMOTE_OTHER
    = NETWORK_DISCONNECT_REMOTE_TIMEOUT_CONNECTING
  pred NETWORK_DISCONNECT_REMOTE_BADCRYPT
    = NETWORK_DISCONNECT_REMOTE_OTHER
  pred NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED
    = NETWORK_DISCONNECT_REMOTE_BADCRYPT
  pred NETWORK_DISCONNECT_UNUSUAL
    = NETWORK_DISCONNECT_REMOTE_CERTNOTTRUSTED
  pred NETWORK_DISCONNECT_INTERNAL_ERROR = NETWORK_DISCONNECT_UNUSUAL
  pred NETWORK_DISCONNECT_REJECT_BADCHALLENGE
    = NETWORK_DISCONNECT_INTERNAL_ERROR
  pred NETWORK_DISCONNECT_REJECT_NOLOBBY
    = NETWORK_DISCONNECT_REJECT_BADCHALLENGE
  pred NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP
    = NETWORK_DISCONNECT_REJECT_NOLOBBY
  pred NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER
    = NETWORK_DISCONNECT_REJECT_BACKGROUND_MAP
  pred NETWORK_DISCONNECT_REJECT_HIDDEN_GAME
    = NETWORK_DISCONNECT_REJECT_SINGLE_PLAYER
  pred NETWORK_DISCONNECT_REJECT_LANRESTRICT
    = NETWORK_DISCONNECT_REJECT_HIDDEN_GAME
  pred NETWORK_DISCONNECT_REJECT_BADPASSWORD
    = NETWORK_DISCONNECT_REJECT_LANRESTRICT
  pred NETWORK_DISCONNECT_REJECT_SERVERFULL
    = NETWORK_DISCONNECT_REJECT_BADPASSWORD
  pred NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION
    = NETWORK_DISCONNECT_REJECT_SERVERFULL
  pred NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL
    = NETWORK_DISCONNECT_REJECT_INVALIDRESERVATION
  pred NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY
    = NETWORK_DISCONNECT_REJECT_FAILEDCHANNEL
  pred NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY
    = NETWORK_DISCONNECT_REJECT_CONNECT_FROM_LOBBY
  pred NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH
    = NETWORK_DISCONNECT_REJECT_RESERVED_FOR_LOBBY
  pred NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
    = NETWORK_DISCONNECT_REJECT_INVALIDKEYLENGTH
  pred NETWORK_DISCONNECT_REJECT_NEWPROTOCOL
    = NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
  pred NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION
    = NETWORK_DISCONNECT_REJECT_NEWPROTOCOL
  pred NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN
    = NETWORK_DISCONNECT_REJECT_INVALIDCONNECTION
  pred NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN
    = NETWORK_DISCONNECT_REJECT_INVALIDCERTLEN
  pred NETWORK_DISCONNECT_REJECT_STEAM
    = NETWORK_DISCONNECT_REJECT_INVALIDSTEAMCERTLEN
  pred NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED
    = NETWORK_DISCONNECT_REJECT_STEAM
  pred NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID
    = NETWORK_DISCONNECT_REJECT_SERVERAUTHDISABLED
  pred NETWORK_DISCONNECT_REJECT_BANNED
    = NETWORK_DISCONNECT_REJECT_SERVERCDKEYAUTHINVALID
  pred NETWORK_DISCONNECT_KICKED_TEAMKILLING
    = NETWORK_DISCONNECT_REJECT_BANNED
  pred NETWORK_DISCONNECT_KICKED_TK_START
    = NETWORK_DISCONNECT_KICKED_TEAMKILLING
  pred NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT
    = NETWORK_DISCONNECT_KICKED_TK_START
  pred NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT
    = NETWORK_DISCONNECT_KICKED_UNTRUSTEDACCOUNT
  pred NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN
    = NETWORK_DISCONNECT_KICKED_CONVICTEDACCOUNT
  pred NETWORK_DISCONNECT_KICKED_TEAMHURTING
    = NETWORK_DISCONNECT_KICKED_COMPETITIVECOOLDOWN
  pred NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING
    = NETWORK_DISCONNECT_KICKED_TEAMHURTING
  pred NETWORK_DISCONNECT_KICKED_VOTEDOFF
    = NETWORK_DISCONNECT_KICKED_HOSTAGEKILLING
  pred NETWORK_DISCONNECT_KICKED_IDLE
    = NETWORK_DISCONNECT_KICKED_VOTEDOFF
  pred NETWORK_DISCONNECT_KICKED_SUICIDE
    = NETWORK_DISCONNECT_KICKED_IDLE
  pred NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN
    = NETWORK_DISCONNECT_KICKED_SUICIDE
  pred NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET
    = NETWORK_DISCONNECT_KICKED_NOSTEAMLOGIN
  pred NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION
    = NETWORK_DISCONNECT_KICKED_NOSTEAMTICKET
  pred NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR
    = NETWORK_DISCONNECT_KICKED_INPUTAUTOMATION
  pred NETWORK_DISCONNECT_KICKED_INSECURECLIENT
    = NETWORK_DISCONNECT_KICKED_VACNETABNORMALBEHAVIOR
  enumFrom = Data.ProtoLens.Message.Enum.messageEnumFrom
  enumFromTo = Data.ProtoLens.Message.Enum.messageEnumFromTo
  enumFromThen = Data.ProtoLens.Message.Enum.messageEnumFromThen
  enumFromThenTo = Data.ProtoLens.Message.Enum.messageEnumFromThenTo
instance Data.ProtoLens.FieldDefault ENetworkDisconnectionReason where
  fieldDefault = NETWORK_DISCONNECT_INVALID
instance Control.DeepSeq.NFData ENetworkDisconnectionReason where
  rnf x__ = Prelude.seq x__ ()