Cabal-version:      3.0

name:               invoker-debug
version:            0.0.0.1

build-type:         Simple
license:            BSD-3-Clause

common exts
  default-extensions:
    BlockArguments
    DeriveAnyClass
    DuplicateRecordFields
    RecordWildCards
    OverloadedRecordDot
    NoFieldSelectors

Flag dev
  Description: Dumps Core representation
  Default:     False
  Manual:      True

executable invoker-debug
  import: exts
  default-language: GHC2021
  main-is: invoker-debug.hs
  build-depends:
      base >=4.7 && <5
    , binary-buff
    , http-client
    , invoker-dota2
    , invoker-steam
  ghc-options:
    -threaded
    -O2
    -Wall
    -Wunused-packages
    -rtsopts
  if impl(ghc >= 9.4)
    ghc-prof-options:
      -fprof-late
  ghc-prof-options:
    "-with-rtsopts=-s -A8m -AL8m -p -hc -L250 -l-agu -N1"
