Cabal-version:      3.0

name:               invoker-proto
version:            0.0.0.1

build-type:         Simple
license:            BSD-3-Clause


Library
  default-language: Haskell2010
  hs-source-dirs:
    .
  ghc-options:
    -Wall
    -Wunused-packages
    -ddump-to-file
    -ddump-timings
  build-depends:
    -- GHC included libraries
      base >= 4.7 && <5

    , microlens
    , proto-lens
    , proto-lens-runtime
    , lens-family

  exposed-modules:
    Proto.BaseGcmessages
    Proto.BaseGcmessages_Fields
    Proto.CPeer2peerNetmessages
    Proto.CPeer2peerNetmessages_Fields
    Proto.Clientmessages
    Proto.Clientmessages_Fields
    Proto.ConnectionlessNetmessages
    Proto.ConnectionlessNetmessages_Fields
    Proto.Demo
    Proto.Demo_Fields
    Proto.DotaBroadcastmessages
    Proto.DotaBroadcastmessages_Fields
    Proto.DotaClientEnums
    Proto.DotaClientEnums_Fields
    Proto.DotaClientmessages
    Proto.DotaClientmessages_Fields
    Proto.DotaCommonmessages
    Proto.DotaCommonmessages_Fields
    Proto.DotaFightingGameP2pMessages
    Proto.DotaFightingGameP2pMessages_Fields
    Proto.DotaGcmessagesClient
    Proto.DotaGcmessagesClientBingo
    Proto.DotaGcmessagesClientBingo_Fields
    Proto.DotaGcmessagesClientCandyShop
    Proto.DotaGcmessagesClientCandyShop_Fields
    Proto.DotaGcmessagesClientChat
    Proto.DotaGcmessagesClientChat_Fields
    Proto.DotaGcmessagesClientCoaching
    Proto.DotaGcmessagesClientCoaching_Fields
    Proto.DotaGcmessagesClientCraftworks
    Proto.DotaGcmessagesClientCraftworks_Fields
    Proto.DotaGcmessagesClientFantasy
    Proto.DotaGcmessagesClientFantasy_Fields
    Proto.DotaGcmessagesClientGuild
    Proto.DotaGcmessagesClientGuildEvents
    Proto.DotaGcmessagesClientGuildEvents_Fields
    Proto.DotaGcmessagesClientGuild_Fields
    Proto.DotaGcmessagesClientMatchManagement
    Proto.DotaGcmessagesClientMatchManagement_Fields
    Proto.DotaGcmessagesClientShowcase
    Proto.DotaGcmessagesClientShowcase_Fields
    Proto.DotaGcmessagesClientTeam
    Proto.DotaGcmessagesClientTeam_Fields
    Proto.DotaGcmessagesClientTournament
    Proto.DotaGcmessagesClientTournament_Fields
    Proto.DotaGcmessagesClientWatch
    Proto.DotaGcmessagesClientWatch_Fields
    Proto.DotaGcmessagesClient_Fields
    Proto.DotaGcmessagesCommon
    Proto.DotaGcmessagesCommonBattleReport
    Proto.DotaGcmessagesCommonBattleReport_Fields
    Proto.DotaGcmessagesCommonCraftworks
    Proto.DotaGcmessagesCommonCraftworks_Fields
    Proto.DotaGcmessagesCommonFightingGame
    Proto.DotaGcmessagesCommonFightingGame_Fields
    Proto.DotaGcmessagesCommonLeague
    Proto.DotaGcmessagesCommonLeague_Fields
    Proto.DotaGcmessagesCommonLobby
    Proto.DotaGcmessagesCommonLobby_Fields
    Proto.DotaGcmessagesCommonMatchManagement
    Proto.DotaGcmessagesCommonMatchManagement_Fields
    Proto.DotaGcmessagesCommonMonsterHunter
    Proto.DotaGcmessagesCommonMonsterHunter_Fields
    Proto.DotaGcmessagesCommonOverworld
    Proto.DotaGcmessagesCommonOverworld_Fields
    Proto.DotaGcmessagesCommonSurvivors
    Proto.DotaGcmessagesCommonSurvivors_Fields
    Proto.DotaGcmessagesCommon_Fields
    Proto.DotaGcmessagesMsgid
    Proto.DotaGcmessagesMsgid_Fields
    Proto.DotaGcmessagesServer
    Proto.DotaGcmessagesServer_Fields
    Proto.DotaGcmessagesWebapi
    Proto.DotaGcmessagesWebapi_Fields
    Proto.DotaHudTypes
    Proto.DotaHudTypes_Fields
    Proto.DotaMatchMetadata
    Proto.DotaMatchMetadata_Fields
    Proto.DotaModifiers
    Proto.DotaModifiers_Fields
    Proto.DotaScenariomessages
    Proto.DotaScenariomessages_Fields
    Proto.DotaSharedEnums
    Proto.DotaSharedEnums_Fields
    Proto.DotaUsercmd
    Proto.DotaUsercmd_Fields
    Proto.DotaUsermessages
    Proto.DotaUsermessages_Fields
    Proto.EconGcmessages
    Proto.EconGcmessages_Fields
    Proto.EconSharedEnums
    Proto.EconSharedEnums_Fields
    Proto.EngineGcmessages
    Proto.EngineGcmessages_Fields
    Proto.EnumsClientserver
    Proto.EnumsClientserver_Fields
    Proto.Gameevents
    Proto.Gameevents_Fields
    Proto.GcsdkGcmessages
    Proto.GcsdkGcmessages_Fields
    Proto.Gcsystemmsgs
    Proto.Gcsystemmsgs_Fields
    Proto.Netmessages
    Proto.Netmessages_Fields
    Proto.NetworkConnection
    Proto.NetworkConnection_Fields
    Proto.Networkbasetypes
    Proto.Networkbasetypes_Fields
    Proto.NetworksystemProtomessages
    Proto.NetworksystemProtomessages_Fields
    Proto.PredictionEvents
    Proto.PredictionEvents_Fields
    Proto.SteamdatagramMessagesAuth
    Proto.SteamdatagramMessagesAuth_Fields
    Proto.SteamdatagramMessagesSdr
    Proto.SteamdatagramMessagesSdr_Fields
    Proto.Steammessages
    Proto.SteammessagesCloud.Steamworkssdk
    Proto.SteammessagesCloud.Steamworkssdk_Fields
    Proto.SteammessagesGamenetworkingui
    Proto.SteammessagesGamenetworkingui_Fields
    Proto.SteammessagesHelprequest.Steamworkssdk
    Proto.SteammessagesHelprequest.Steamworkssdk_Fields
    Proto.SteammessagesInt
    Proto.SteammessagesInt_Fields
    Proto.SteammessagesOauth.Steamworkssdk
    Proto.SteammessagesOauth.Steamworkssdk_Fields
    Proto.SteammessagesPlayer.Steamworkssdk
    Proto.SteammessagesPlayer.Steamworkssdk_Fields
    Proto.SteammessagesPublishedfile.Steamworkssdk
    Proto.SteammessagesPublishedfile.Steamworkssdk_Fields
    Proto.SteammessagesSteamlearn.Steamworkssdk
    Proto.SteammessagesSteamlearn.Steamworkssdk_Fields
    Proto.SteammessagesUnifiedBase.Steamworkssdk
    Proto.SteammessagesUnifiedBase.Steamworkssdk_Fields
    Proto.Steammessages_Fields
    Proto.SteamnetworkingsocketsMessages
    Proto.SteamnetworkingsocketsMessagesCerts
    Proto.SteamnetworkingsocketsMessagesCerts_Fields
    Proto.SteamnetworkingsocketsMessagesUdp
    Proto.SteamnetworkingsocketsMessagesUdp_Fields
    Proto.SteamnetworkingsocketsMessages_Fields
    Proto.Te
    Proto.Te_Fields
    Proto.UifontfileFormat
    Proto.UifontfileFormat_Fields
    Proto.Usercmd
    Proto.Usercmd_Fields
    Proto.Usermessages
    Proto.Usermessages_Fields
    Proto.Valveextensions
    Proto.Valveextensions_Fields

