Cabal-version:      3.0

name:               invoker
version:            0.0.0.1

build-type:         Simple
license:            BSD-3-Clause


Library
  default-language: GHC2021
  exposed-modules:
    Invoker
  other-modules:
    Invoker.Binary
    Invoker.Parser
  hs-source-dirs:
    ./library/
  ghc-options:
    -Wall
    -Wunused-packages
  build-depends:
    -- GHC included libraries
      base >= 4.7 && <5
    , binary
    , bytestring

    -- Internal
    , invoker-proto

    -- External
    , snappy
    , proto-lens

executable invoker
  default-language: GHC2021
  main-is: invoker.hs
  build-depends:
      base >=4.7 && <5
    , bytestring
    , invoker
  ghc-options:
    -threaded
    -O2
    -Wall
    -Wunused-packages
    -rtsopts
    "-with-rtsopts=-T -A8m -AL32m -N2"
