Cabal-version:      3.0

name:               invoker-dota2
version:            0.0.0.1

build-type:         Simple
license:            BSD-3-Clause

common exts
  default-extensions:
    BlockArguments
    DeriveAnyClass
    DuplicateRecordFields
    RecordWildCards
    OverloadedRecordDot
    NoFieldSelectors

Flag dev
  Description: Dumps Core representation
  Default:     False
  Manual:      True

Library
  import: exts
  default-language: GHC2021
  exposed-modules:
    Invoker
  other-modules:
    Invoker.DotaGC
    Invoker.Parser
    Invoker.Parser.DemoPacket
    Invoker.Parser.Entity
    Invoker.Parser.Quantized
    Invoker.Parser.SendTables
  hs-source-dirs:
    ./library/
  ghc-options:
    -Wall
    -Wunused-packages
  build-depends:
    -- GHC included libraries
      base >= 4.7 && <5
    , bytestring
    , text
    , vector
    , containers

    -- Internal
    , invoker-dota2-proto
    , binary-buff

    -- External
    , snappy
    , proto-lens
    , lens-family
    , unordered-containers

  if flag(dev)
    GHC-Options:
      -ddump-to-file
      -ddump-timings
      -ddump-simpl
      -ddump-spec
      -ddump-simpl-stats
      -ddump-rule-firings
      -dsuppress-all
      -dsuppress-uniques
    if impl(ghc >= 9.4)
      ghc-options:
        -dlint
        -dno-suppress-core-sizes

test-suite invoker-tests
  type:             exitcode-stdio-1.0
  main-is:          tests.hs
  build-depends:    base
  default-language: GHC2021
