Cabal-version:      3.0

name:               invoker-steam-proto
version:            0.0.0.1

build-type:         Simple
license:            BSD-3-Clause

Flag dev
  Description: Dumps Core representation
  Default:     False
  Manual:      True

Library
  default-language: Haskell2010
  hs-source-dirs:
    .
  ghc-options:
    -Wall
    -Wunused-packages
  if impl(ghc >= 9.4)
    ghc-prof-options:
      -fprof-late
  ghc-prof-options:
    "-with-rtsopts=-s -A8m -AL8m -p -hc -L250 -l-agu -N1"

  if flag(dev)
    GHC-Options:
      -ddump-to-file
      -ddump-timings
      -ddump-simpl
      -ddump-spec
      -ddump-simpl-stats
      -ddump-rule-firings
      -dsuppress-all
      -dsuppress-uniques
      -ddump-to-file
      -ddump-timings
    if impl(ghc >= 9.4)
      ghc-options:
        -dlint
        -dno-suppress-core-sizes

  build-depends:
    proto-lens-runtime

  exposed-modules:
    Proto.Clientmetrics
    Proto.Clientmetrics_Fields
    Proto.ContentManifest
    Proto.ContentManifest_Fields
    Proto.Contenthubs
    Proto.Contenthubs_Fields
    Proto.EncryptedAppTicket
    Proto.EncryptedAppTicket_Fields
    Proto.Enums
    Proto.EnumsClientserver
    Proto.EnumsClientserver_Fields
    Proto.EnumsProductinfo
    Proto.EnumsProductinfo_Fields
    Proto.Enums_Fields
    Proto.Htmlmessages
    Proto.Htmlmessages_Fields
    Proto.OfflineTicket
    Proto.OfflineTicket_Fields
    Proto.SteamdatagramMessagesAuth
    Proto.SteamdatagramMessagesAuth_Fields
    Proto.SteamdatagramMessagesSdr
    Proto.SteamdatagramMessagesSdr_Fields
    Proto.SteammessagesAccounthardware.Steamclient
    Proto.SteammessagesAccounthardware.Steamclient_Fields
    Proto.SteammessagesAppoverview
    Proto.SteammessagesAppoverview_Fields
    Proto.SteammessagesAuth.Steamclient
    Proto.SteammessagesAuth.Steamclient_Fields
    Proto.SteammessagesBase
    Proto.SteammessagesBase_Fields
    Proto.SteammessagesBroadcast.Steamclient
    Proto.SteammessagesBroadcast.Steamclient_Fields
    Proto.SteammessagesChat.Steamclient
    Proto.SteammessagesChat.Steamclient_Fields
    Proto.SteammessagesChildprocessquery
    Proto.SteammessagesChildprocessquery_Fields
    Proto.SteammessagesClientObjects
    Proto.SteammessagesClientObjects_Fields
    Proto.SteammessagesClientlanp2p
    Proto.SteammessagesClientlanp2p_Fields
    Proto.SteammessagesClientmetrics.Steamclient
    Proto.SteammessagesClientmetrics.Steamclient_Fields
    Proto.SteammessagesClientnotificationtypes
    Proto.SteammessagesClientnotificationtypes_Fields
    Proto.SteammessagesClientserver
    Proto.SteammessagesClientserver2
    Proto.SteammessagesClientserver2_Fields
    Proto.SteammessagesClientserverAppinfo
    Proto.SteammessagesClientserverAppinfo_Fields
    Proto.SteammessagesClientserverFriends
    Proto.SteammessagesClientserverFriends_Fields
    Proto.SteammessagesClientserverGameservers
    Proto.SteammessagesClientserverGameservers_Fields
    Proto.SteammessagesClientserverLbs
    Proto.SteammessagesClientserverLbs_Fields
    Proto.SteammessagesClientserverLogin
    Proto.SteammessagesClientserverLogin_Fields
    Proto.SteammessagesClientserverMms
    Proto.SteammessagesClientserverMms_Fields
    Proto.SteammessagesClientserverUcm
    Proto.SteammessagesClientserverUcm_Fields
    Proto.SteammessagesClientserverUds
    Proto.SteammessagesClientserverUds_Fields
    Proto.SteammessagesClientserverUserstats
    Proto.SteammessagesClientserverUserstats_Fields
    Proto.SteammessagesClientserverVideo
    Proto.SteammessagesClientserverVideo_Fields
    Proto.SteammessagesClientserver_Fields
    Proto.SteammessagesClientsettings
    Proto.SteammessagesClientsettings_Fields
    Proto.SteammessagesCloud.Steamclient
    Proto.SteammessagesCloud.Steamclient_Fields
    Proto.SteammessagesCommunity.Steamclient
    Proto.SteammessagesCommunity.Steamclient_Fields
    Proto.SteammessagesContentsystem.Steamclient
    Proto.SteammessagesContentsystem.Steamclient_Fields
    Proto.SteammessagesCredentials.Steamclient
    Proto.SteammessagesCredentials.Steamclient_Fields
    Proto.SteammessagesDatapublisher.Steamclient
    Proto.SteammessagesDatapublisher.Steamclient_Fields
    Proto.SteammessagesDepotbuilder.Steamclient
    Proto.SteammessagesDepotbuilder.Steamclient_Fields
    Proto.SteammessagesEcon.Steamclient
    Proto.SteammessagesEcon.Steamclient_Fields
    Proto.SteammessagesFamilygroups.Steamclient
    Proto.SteammessagesFamilygroups.Steamclient_Fields
    Proto.SteammessagesFriendmessages.Steamclient
    Proto.SteammessagesFriendmessages.Steamclient_Fields
    Proto.SteammessagesGamenetworking.Steamclient
    Proto.SteammessagesGamenetworking.Steamclient_Fields
    Proto.SteammessagesGamenetworkingui
    Proto.SteammessagesGamenetworkingui_Fields
    Proto.SteammessagesGamenotifications.Steamclient
    Proto.SteammessagesGamenotifications.Steamclient_Fields
    Proto.SteammessagesGamerecording.Steamclient
    Proto.SteammessagesGamerecording.Steamclient_Fields
    Proto.SteammessagesGamerecordingObjects
    Proto.SteammessagesGamerecordingObjects_Fields
    Proto.SteammessagesGameservers.Steamclient
    Proto.SteammessagesGameservers.Steamclient_Fields
    Proto.SteammessagesHiddevices
    Proto.SteammessagesHiddevices_Fields
    Proto.SteammessagesInventory.Steamclient
    Proto.SteammessagesInventory.Steamclient_Fields
    Proto.SteammessagesLinkfilter.Steamclient
    Proto.SteammessagesLinkfilter.Steamclient_Fields
    Proto.SteammessagesLobbymatchmaking.Steamclient
    Proto.SteammessagesLobbymatchmaking.Steamclient_Fields
    Proto.SteammessagesMarket.Steamclient
    Proto.SteammessagesMarket.Steamclient_Fields
    Proto.SteammessagesMarketingmessages.Steamclient
    Proto.SteammessagesMarketingmessages.Steamclient_Fields
    Proto.SteammessagesNotifications.Steamclient
    Proto.SteammessagesNotifications.Steamclient_Fields
    Proto.SteammessagesOffline.Steamclient
    Proto.SteammessagesOffline.Steamclient_Fields
    Proto.SteammessagesParental.Steamclient
    Proto.SteammessagesParental.Steamclient_Fields
    Proto.SteammessagesParentalObjects
    Proto.SteammessagesParentalObjects_Fields
    Proto.SteammessagesParties.Steamclient
    Proto.SteammessagesParties.Steamclient_Fields
    Proto.SteammessagesPartnerapps.Steamclient
    Proto.SteammessagesPartnerapps.Steamclient_Fields
    Proto.SteammessagesPlayer.Steamclient
    Proto.SteammessagesPlayer.Steamclient_Fields
    Proto.SteammessagesPublishedfile.Steamclient
    Proto.SteammessagesPublishedfile.Steamclient_Fields
    Proto.SteammessagesQms.Steamclient
    Proto.SteammessagesQms.Steamclient_Fields
    Proto.SteammessagesRemoteclient
    Proto.SteammessagesRemoteclientDiscovery
    Proto.SteammessagesRemoteclientDiscovery_Fields
    Proto.SteammessagesRemoteclientService.Steamclient
    Proto.SteammessagesRemoteclientService.Steamclient_Fields
    Proto.SteammessagesRemoteclientServiceMessages
    Proto.SteammessagesRemoteclientServiceMessages_Fields
    Proto.SteammessagesRemoteclient_Fields
    Proto.SteammessagesRemoteplay
    Proto.SteammessagesRemoteplay_Fields
    Proto.SteammessagesSecrets.Steamclient
    Proto.SteammessagesSecrets.Steamclient_Fields
    Proto.SteammessagesShader.Steamclient
    Proto.SteammessagesShader.Steamclient_Fields
    Proto.SteammessagesSiteLicense.Steamclient
    Proto.SteammessagesSiteLicense.Steamclient_Fields
    Proto.SteammessagesSitelicenseclient
    Proto.SteammessagesSitelicenseclient_Fields
    Proto.SteammessagesSiteserverui
    Proto.SteammessagesSiteserverui_Fields
    Proto.SteammessagesSteamtv.Steamclient
    Proto.SteammessagesSteamtv.Steamclient_Fields
    Proto.SteammessagesStore.Steamclient
    Proto.SteammessagesStore.Steamclient_Fields
    Proto.SteammessagesStorebrowse.Steamclient
    Proto.SteammessagesStorebrowse.Steamclient_Fields
    Proto.SteammessagesTimedtrial.Steamclient
    Proto.SteammessagesTimedtrial.Steamclient_Fields
    Proto.SteammessagesTwofactor.Steamclient
    Proto.SteammessagesTwofactor.Steamclient_Fields
    Proto.SteammessagesUnifiedBase.Steamclient
    Proto.SteammessagesUnifiedBase.Steamclient_Fields
    Proto.SteammessagesUnifiedTest.Steamclient
    Proto.SteammessagesUnifiedTest.Steamclient_Fields
    Proto.SteammessagesUseraccount.Steamclient
    Proto.SteammessagesUseraccount.Steamclient_Fields
    Proto.SteammessagesVac.Steamclient
    Proto.SteammessagesVac.Steamclient_Fields
    Proto.SteammessagesVideo.Steamclient
    Proto.SteammessagesVideo.Steamclient_Fields
    Proto.SteammessagesVirtualcontroller
    Proto.SteammessagesVirtualcontroller_Fields
    Proto.SteammessagesWorkshop.Steamclient
    Proto.SteammessagesWorkshop.Steamclient_Fields
    Proto.SteamnetworkingsocketsMessages
    Proto.SteamnetworkingsocketsMessagesCerts
    Proto.SteamnetworkingsocketsMessagesCerts_Fields
    Proto.SteamnetworkingsocketsMessagesUdp
    Proto.SteamnetworkingsocketsMessagesUdp_Fields
    Proto.SteamnetworkingsocketsMessages_Fields
    Proto.WebuimessagesAchievements
    Proto.WebuimessagesAchievements_Fields
    Proto.WebuimessagesAudio
    Proto.WebuimessagesAudio_Fields
    Proto.WebuimessagesBase
    Proto.WebuimessagesBase_Fields
    Proto.WebuimessagesBluetooth
    Proto.WebuimessagesBluetooth_Fields
    Proto.WebuimessagesGamenotes
    Proto.WebuimessagesGamenotes_Fields
    Proto.WebuimessagesGamerecording
    Proto.WebuimessagesGamerecording_Fields
    Proto.WebuimessagesGamerecordingfiles
    Proto.WebuimessagesGamerecordingfiles_Fields
    Proto.WebuimessagesGamescope
    Proto.WebuimessagesGamescope_Fields
    Proto.WebuimessagesHardwareupdate
    Proto.WebuimessagesHardwareupdate_Fields
    Proto.WebuimessagesLeds
    Proto.WebuimessagesLeds_Fields
    Proto.WebuimessagesScreensaver
    Proto.WebuimessagesScreensaver_Fields
    Proto.WebuimessagesSharedjscontext
    Proto.WebuimessagesSharedjscontext_Fields
    Proto.WebuimessagesSleep
    Proto.WebuimessagesSleep_Fields
    Proto.WebuimessagesSteamengine
    Proto.WebuimessagesSteamengine_Fields
    Proto.WebuimessagesSteaminput
    Proto.WebuimessagesSteaminput_Fields
    Proto.WebuimessagesSteamos
    Proto.WebuimessagesSteamos_Fields
    Proto.WebuimessagesStoragedevicemanager
    Proto.WebuimessagesStoragedevicemanager_Fields
    Proto.WebuimessagesSystemmanager
    Proto.WebuimessagesSystemmanager_Fields
    Proto.WebuimessagesTransport
    Proto.WebuimessagesTransport_Fields
    Proto.WebuimessagesTransportvalidation
    Proto.WebuimessagesTransportvalidation_Fields
    Proto.WebuimessagesUser
    Proto.WebuimessagesUser_Fields


